### PR TITLE
Nus templates

### PR DESCRIPTION
**Pull request by ccewuz**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Pre-merge checks

- [ ] Did not modify any files outside of your organisation's template folder (e.g package-lock.json or anything else)
- [ ] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [ ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [ ] `npm run test` passes
- [ ] `npm run test:integration` passes
- [ ] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### Certificate Template 
- [ ] No more than 5 templates or 25 added/modified files in the pull request
- [ ] Ensure that your .opencert file's data complies with the intentions of the OpenCerts' schema - e.g recipient related information is inside the `recipient` object, etc.
- [ ] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [ ] Sample certificate file included for each template, located alongside the integration test for each template
- [ ] Sample certificates must obviously be a sample certificate
  - [ ] Obviously fictitious name
  - [ ] Obviously sample signatory images
- [ ] No fixed-size raster images as part of certificate layout
- [ ] Mobile responsive design
- [ ] Date parsing should be localised to template author's timezone
- [ ] Webpack chunking code is correct
  - [ ] Has chunking code
  - [ ] Same chunking code as the other certificates belonging to that institute
- [ ] Certificate Store Addresses have been updated
  - [ ] Template Whitelist
  - [ ] Registry
- [ ] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### CODE REVIEW

**Comment by Nebulis** [comment]
can rebase first please ?

**Comment by ccewuz** [comment]
Okay, done.

**Comment by Nebulis** [comment]
can you rebase again ? There are conflicts

**Comment by ccewuz** [comment]
may I know what are the conflicts?

**Comment by Nebulis** [comment]
Unfortunately I dunno

image

**Comment by Nebulis** [comment]
Nothing happens if you run the following ? (supposing upstream is set to this repo): 

```
git fetch upstream
git rebase upstream/master
```

**Comment by ccewuz** [comment]
ok i have done the rebase again. Any conflicts?

**Comment by Nebulis** [comment]
Yes still conflicts. There is also more files that changed than before and more commits.

There are may old commits that I think I've already been merged, for instance:

image

I would advise you to create a new branch and a new MR to start clean:
- update your own master branch and make sure it's to date with this master repository
- create a new branch from your master
- cherry pick commits that you need
- create a new MR

**Comment by ccewuz** [comment]
I tried to rebase again, and saw "Your branch and 'origin/nus-templates' have diverged, and have 3 and 50 different commits each, respectively.  (use "git pull" to merge the remote branch into yours)". 

So I followed it, and got "Your branch is ahead of 'origin/nus-templates' by 4 commits.  (use "git push" to publish your local commits)". 

I followed again and got "Your branch is up to date with 'origin/nus-templates'.". 

On web UI, I can see "This branch has no conflicts with the base branch", so it is very strange there are still conflicts, because otherwise I should have a change to solve it.

**Comment by Nebulis** [comment]
`"Your branch and 'origin/nus-templates' have diverged` => this explains why there is so much commit in the MR. I guess that you created this branch from `origin/nus-templates` which you rebased and then when you also rebased this branch they had diverged which led to git adding some commit twice.
```
I would advise you to create a new branch and a new MR to start clean:
- update your own master branch and make sure it's to date with this master repository
- create a new branch from your master
- cherry pick commits that you need
- create a new MR
```

I really recommend you this.

**Comment by ccewuz** [comment]
close due to opening of nus-templates-new

**Pull request closed without merging**
