### PR TITLE
new templates for 2017 FT BMS PHARM graduates

### PR DESCRIPTION
**Pull request by mmysgp**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository to cater for 2017 BMS/PHARM  graduates
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Pre-merge checks

- [x] Did not modify any files outside of your organisation's template folder (e.g package-lock.json or anything else)
- [x] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [ ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [x] `npm run test` passes
- [ ] `npm run test:integration` passes
- [x] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### Certificate Template 
- [x] No more than 5 templates or 25 added/modified files in the pull request
- [x] Ensure that your .opencert file's data complies with the intentions of the OpenCerts' schema - e.g recipient related information is inside the `recipient` object, etc.
- [x] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [x] Sample certificate file included for each template, located alongside the integration test for each template
- [x] Sample certificates must obviously be a sample certificate
  - [ ] Obviously fictitious name
  - [ ] Obviously sample signatory images
- [x] No fixed-size raster images as part of certificate layout
- [x] Mobile responsive design
- [x] Date parsing should be localised to template author's timezone
- [x] Webpack chunking code is correct
  - [ ] Has chunking code
  - [ ] Same chunking code as the other certificates belonging to that institute
- [ ] Certificate Store Addresses have been updated
  - [ ] Template Whitelist
  - [ ] Registry
- [x] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### CODE REVIEW

**Comment by mmysgp** [comment]
We can use raw JSON to test the template while the file used for Integration Test must be signed JSON.
It's a bit confusing. Suggest to update the Integration Test Document to make it clear.

**Comment by rjchow** [comment]
Thanks for the feedback, I will update the documentation to reflect that

Is this PR ready for review?

**Comment by mmysgp** [comment]
Yes. Please migrate it to PRD if no issues.
Thanks.

**Comment by rjchow** [comment]
code looks ok but the merkleRoot of the test certs haven't been issued on the cert's store address?

**Comment by mmysgp** [comment]
Just issued on TestNet. Please verify.

**Comment by rjchow** [comment]
looks good, thanks.
Merging

**Pull request merged**
