### PR TITLE
Nus templates new

### PR DESCRIPTION
**Pull request by ccewuz**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Pre-merge checks

- [ ] Did not modify any files outside of your organisation's template folder (e.g package-lock.json or anything else)
- [ ] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [ ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [ ] `npm run test` passes
- [ ] `npm run test:integration` passes
- [ ] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### Certificate Template 
- [ ] No more than 5 templates or 25 added/modified files in the pull request
- [ ] Ensure that your .opencert file's data complies with the intentions of the OpenCerts' schema - e.g recipient related information is inside the `recipient` object, etc.
- [ ] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [ ] Sample certificate file included for each template, located alongside the integration test for each template
- [ ] Sample certificates must obviously be a sample certificate
  - [ ] Obviously fictitious name
  - [ ] Obviously sample signatory images
- [ ] No fixed-size raster images as part of certificate layout
- [ ] Mobile responsive design
- [ ] Date parsing should be localised to template author's timezone
- [ ] Webpack chunking code is correct
  - [ ] Has chunking code
  - [ ] Same chunking code as the other certificates belonging to that institute
- [ ] Certificate Store Addresses have been updated
  - [ ] Template Whitelist
  - [ ] Registry
- [ ] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### CODE REVIEW

**Comment by Nebulis** [comment]
It's better but I still can't rebase :sweat_smile: .

I see 8 commits, the only you are interested in is https://github.com/OpenCerts/legacy-templates/pull/38/commits/633d1d1bbbaada32d701aa889511660c651ae3ef

Try to run the following on your repository:
1. Syncinc your local repo (https://help.github.com/en/articles/syncing-a-fork)
```shell
git checkout master
git fetch upstream # I supposed you setup correctly upstream to this repository
git merge upstream/master
```
At this point, your fork must be completed up to date with this repo

2. Create a branch
```
git branch -D nus-template-new # (let's reuse this branch)
git checkout -b nus-template-new
git cherry-pick 633d1d1bbbaada32d701aa889511660c651ae3ef 
# make sure your branch has the commit and everything looks correct
git push --set-upstream origin nus-template-new --force #only do this if everything is ok
```

**Comment by ccewuz** [comment]
Thanks for tips. Below are commands executed and logs

>git checkout master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)

>git fetch upstream

>git merge upstream/master
Merge made by the 'recursive' strategy.

>git branch -D nus-templates-new
Deleted branch nus-templates-new (was 633d1d1).

>git checkout -b nus-template-new
Switched to a new branch 'nus-template-new'

>git cherry-pick 633d1d1bbbaada32d701aa889511660c651ae3ef
[nus-template-new 2afecdb] 20191004 NUS Templates batch 5
 Date: Fri Oct 4 14:44:27 2019 +0800
 27 files changed, 4939 insertions(+)
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-DUKENUS-2019/degree.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-DUKENUS-2019/degree.scss
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-DUKENUS-2019/index.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-DUKENUS-2019/integration.spec.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-DUKENUS-2019/sample.opencert
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K14UEJDP-2019/degree.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K14UEJDP-2019/index.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K14UEJDP-2019/integration.spec.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K14UEJDP-2019/sample.opencert
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K15HUJIJDP-2019/degree.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K15HUJIJDP-2019/index.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K15HUJIJDP-2019/integration.spec.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K15HUJIJDP-2019/sample.opencert
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K18KCLJDP-2019/degree.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K18KCLJDP-2019/index.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K18KCLJDP-2019/integration.spec.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K18KCLJDP-2019/sample.opencert
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K22SJTUJDP-2019/degree.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K22SJTUJDP-2019/index.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K22SJTUJDP-2019/integration.spec.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-K22SJTUJDP-2019/sample.opencert
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-YALE-2019/degree.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-YALE-2019/degree.scss
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-YALE-2019/index.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-YALE-2019/integration.spec.js
 create mode 100644 src/components/CertificateTemplates/tlds/sg/edu/nus/NUS-YALE-2019/sample.opencert

>git push --set-upstream origin nus-template-new --force
Counting objects: 92, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (92/92), done.
Writing objects: 100% (92/92), 77.05 KiB | 1.17 MiB/s, done.
Total 92 (delta 47), reused 0 (delta 0)
remote: Resolving deltas: 100% (47/47), completed with 11 local objects.
remote:
remote: Create a pull request for 'nus-template-new' on GitHub by visiting:
remote:      https://github.com/ccewuz/legacy-templates/pull/new/nus-template-new
remote:
To https://github.com/ccewuz/legacy-templates.git
 * [new branch]      nus-template-new -> nus-template-new
Branch 'nus-template-new' set up to track remote branch 'nus-template-new' from 'origin'.

**Comment by Nebulis** [comment]
Hummmmm there is still something wrong, let's try to update your master first I see it's outdated in your fork

What's happening when you run ?

```shell
git checkout master
git fetch upstream # I supposed you setup correctly upstream to this repository
git merge upstream/master
```

**Comment by ccewuz** [comment]
Have you checked out #39? I tried to push. Is my fork in sync now?

**Comment by Nebulis** [comment]
Yes I've seen #39 and there is still 8 commits. Your master diverged from ours

image

Try this:
```
git fetch upstream
git checkout master
git reset --hard upstream/master  
git push origin master --force 
```

It should force sync your master with ours

**Comment by ccewuz** [comment]
ok done. now should be synced

**Comment by Nebulis** [comment]
image

Yes it is :tada:. Can you try again to update your MR with cherry-pick ?

**Comment by ccewuz** [comment]
ok done

**Comment by Nebulis** [comment]
Great thanks will handle that Monday. Can you close the other PR ? (if not already done)

**Comment by ccewuz** [comment]
Closed the other two. Thank you for your help!

**Pull request merged**
